### PR TITLE
support silversearcher-ag

### PR DESCRIPTION
**Pull request by byplayer**
support silversearcher
https://github.com/ggreer/the_silver_searcher

The current silversearcher has bug, so this script can't work.

I send patch silver searcher.
This version can work properly.
https://github.com/ggreer/the_silver_searcher/pull/351/files

### CODE REVIEW

**Comment by willghatch** [comment]
I like the idea of this source and would like to add it.  When I try to test it, though, zsh crashes on a "double free or corruption" error.  I'm not sure what's causing it, but it happens on both zsh 5.0.7 and zsh 5.0.5.

**Comment by termoshtt** [comment]
@willghatch I cannot reproduce the crash in both zsh 5.0.7 and 5.0.8,
and I confirm it works appropriately.

**Comment by willghatch** [comment]
Hmm, it may be OS dependent.  What OS do you have?  (I'm on Arch Linux).  I'm not sure what to do here -- it would be great for those who have a zsh that doesn't crash on it, but I wouldn't want unsuspecting users to get a nice core dump and potentially closed terminal window and then have them think that zaw sucks.

**Comment by willghatch** [comment]
I just tested on a couple servers I run, one with Debian Stable and one with Ubuntu Trusty (I think that's the current LTS) and I get a double free or corruption error on both.

**Comment by termoshtt** [comment]
I am testing on ArchLinux too.
When I test on ubuntu:latest docker image (Trusty) with smallest .zshrc

```zsh
source $HOME/zaw/zaw.zsh
```

it does not crash though it does not work well because ubuntu use old version of ag (0.19).
(zsh version is 5.0.2)

I suspect that your settings of zsh causes the crash.
Could you test in clean environment?

**Comment by willghatch** [comment]
So some quick printf debugging shows me that it crashes on line 36 of the ag source, where the anonymous function returns.  If I comment out the anonymous function header/ending (IE inlining/lifting the contents of the function) it then crashes at line 67, where the zaw-src-ag function exits.  So... somehow in a very reliable way zsh is crashing on a function return for me.  I don't think I'll take time to compile a debug version of zsh and try to step through it right now.  And besides, I'm terrible with gdb.

But, if I comment out lines 24, 25, 27, and 33 it stops crashing and works fine.  It just adds the ag command that was used to the history.

And since you wrote your last comment while I was writing this, I tested with a clean zshrc and you're quite right.  So I'll have to figure out what in my settings is causing this to crash if it does that history stuff.

**Comment by willghatch** [comment]
Sorry for all the confusion of my setup causing crashes.  I'll have to remember to test things with a minimal environment...

**Pull request merged**
